/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package file;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;

public class Library {

	public static void main(String[] args) throws IOException {
		
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		
		String fileName = br.readLine();
		if(fileName.equals(" ")) {
			System.out.println("File Name Must be Included");
		}
		
		System.out.println(fileName);
		
		File file = new File(fileName);
		
		if(file.exists()) {
			System.out.println("존재하는 파일입니다");
		}else {
			System.out.println(fileName+" is not exist");
		}
		
		
	}
}
