/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package file;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import core.message.ValidationResult;
import displayer.Displayer;
import displayer.SimpleDisplayer;

class displayer {

    @Test
    @DisplayName("displayer 객체를 생성한다.")
    public void test() {
    	
    	Displayer dis = new SimpleDisplayer();
    	assertNotNull(dis);
    }
    
    @Test
    @DisplayName("사용자의 입력을 받아들인다. 이때, TestDisplayerInput인자를 사용해야 한다.")
    public void t2() {
    	
    	String fileName= "dummy.file";
    	
    	
    	Displayer dis = new SimpleDisplayer();
    	dis.input(fileName);
    	assertNotNull(dis.getFileName());
    	
    	
    }
    
    @Test
    @DisplayName("밸리데이션 실패 시, 밸리데이션 실패 메시지를 보여준다")
    public void t3() {
    	Displayer dis = new SimpleDisplayer();
    	ValidationResult r = dis.showResult(new ValidationResult("file.jpg",false));
    	assertNotNull(r);
    }

    
}
